/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poject101;

import java.sql.*;
import java.util.Arrays;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Select extends javax.swing.JFrame {

    /**
     * Creates new form SELECT1
     */
    public Select() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Gender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Select Student ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Faculty");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Select all");

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("StudentID");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String collum=jButton1.getText();
       Connection conn = null;
        try {
            String url = "jdbc:sqlite:northwind.db"; //กำหนด url ของฐานข้อมูล
            conn = DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(null, "Connection Sucess");
            
            String sql = "SELECT * FROM Student WHERE "+collum+" = ?";
            String  fac= jTextField1.getText();//รับ input จาก user
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, fac); //เติม ?
            ResultSet rs = stmt.executeQuery(); //ส่ง sql ไปยังฐานข้อมูล และได้ ResultSet rs
           
           //แสดง ResultSet  บน Table  
            //Reset ข้อมูล ในตาราง   
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnCount(6); //แก้เลข 6
            jTable1.setModel(tableModel);
            //วนลูปบนผลลัพธ์ที่ได้จากฐานข้อมูล
            while(rs.next()){
                //int prodcutId = rs.getInt("ProductID");
                int c1 = rs.getInt("StudentID");
                String c2 = rs.getString("Gender");
                 String c3 = rs.getString("StudentName");
                String c4 = rs.getString("Phone");
                String c5 = rs.getString("Faculty");
                 String c6 = rs.getString("Major");
                
               //สร้างแถว
               Object[] row = {c1,c2,c3,c4,c5,c6,};
               //เพิ่มแถวเข้าไปใน ตาราง
               tableModel.addRow(row);
            }
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 String collum=jButton2.getText();
       Connection conn = null;
        try {
            String url = "jdbc:sqlite:northwind.db"; //กำหนด url ของฐานข้อมูล
            conn = DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(null, "Connection Sucess");
            
            String sql = "SELECT * FROM Student WHERE "+collum+" = ?";
            String  major= jTextField1.getText();//รับ input จาก user
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, major); //เติม ?
            ResultSet rs = stmt.executeQuery(); //ส่ง sql ไปยังฐานข้อมูล และได้ ResultSet rs
           
           //แสดง ResultSet  บน Table  
            //Reset ข้อมูล ในตาราง   
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnCount(6); //แก้เลข 6
            jTable1.setModel(tableModel);
            //วนลูปบนผลลัพธ์ที่ได้จากฐานข้อมูล
            while(rs.next()){
                //int prodcutId = rs.getInt("ProductID");
               int c1 = rs.getInt("StudentID");
                String c2 = rs.getString("Gender");
                 String c3 = rs.getString("StudentName");
                String c4 = rs.getString("Phone");
                String c5 = rs.getString("Faculty");
                 String c6 = rs.getString("Major");
                
               
               //สร้างแถว
               Object[] row = {c1,c2,c3,c4,c5,c6,};
               //เพิ่มแถวเข้าไปใน ตาราง
               tableModel.addRow(row);
            }
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
        try {
            String url = "jdbc:sqlite:northwind.db"; //กำหนด url ของฐานข้อมูล
            conn = DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(null, "Connection Sucess");
            
            String sql = "SELECT * FROM Student";
            PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery(); // ส่ง SQL ไปยังฐานข้อมูล และได้ ResultSet rs

           
           //แสดง ResultSet  บน Table  
            //Reset ข้อมูล ในตาราง   
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnCount(6); //แก้เลข 6
            jTable1.setModel(tableModel);
            //วนลูปบนผลลัพธ์ที่ได้จากฐานข้อมูล
            while(rs.next()){
                //int prodcutId = rs.getInt("ProductID");
               int c1 = rs.getInt("StudentID");
                String c2 = rs.getString("Gender");
                 String c3 = rs.getString("StudentName");
                String c4 = rs.getString("Phone");
                String c5 = rs.getString("Faculty");
                 String c6 = rs.getString("Major");
                
               
               //สร้างแถว
               Object[] row = {c1,c2,c3,c4,c5,c6,};
               //เพิ่มแถวเข้าไปใน ตาราง
               tableModel.addRow(row);
            }
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String collum=jButton4.getText();
       Connection conn = null;
        try {
            String url = "jdbc:sqlite:northwind.db"; //กำหนด url ของฐานข้อมูล
            conn = DriverManager.getConnection(url);
            JOptionPane.showMessageDialog(null, "Connection Sucess");
            
            String sql = "SELECT * FROM Student WHERE "+collum+" = ?";
            String  major= jTextField1.getText();//รับ input จาก user
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, major); //เติม ?
            ResultSet rs = stmt.executeQuery(); //ส่ง sql ไปยังฐานข้อมูล และได้ ResultSet rs
           
           //แสดง ResultSet  บน Table  
            //Reset ข้อมูล ในตาราง   
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnCount(6); //แก้เลข 6
            jTable1.setModel(tableModel);
            //วนลูปบนผลลัพธ์ที่ได้จากฐานข้อมูล
            while(rs.next()){
                //int prodcutId = rs.getInt("ProductID");
               int c1 = rs.getInt("StudentID");
                String c2 = rs.getString("Gender");
                 String c3 = rs.getString("StudentName");
                String c4 = rs.getString("Phone");
                String c5 = rs.getString("Faculty");
                 String c6 = rs.getString("Major");
                
               
               //สร้างแถว
               Object[] row = {c1,c2,c3,c4,c5,c6,};
               //เพิ่มแถวเข้าไปใน ตาราง
               tableModel.addRow(row);
            }
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
